name: weather_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.0
  flutter_gen_runner: ^5.1.6
  flutter_gen: ^5.1.6

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
  assets:
    enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist.ttf